on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Flatpak Nightly
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        if: matrix.arch == 'aarch64'
        run: |
          dnf -y install docker
      - name: Setup QEMU
        if: matrix.arch == 'aarch64'
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Prepare Runtime
        run: |
          flatpak --system update -y --noninteractive
          flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.node20/${{ matrix.arch }}/24.08
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.vixalien.sticky.flatpak
          repository-name: gnome-nightly
          repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
          manifest-path: build-aux/flatpak/com.vixalien.sticky.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
